<html>
<head>
<title>Definir Variables de Diferentes Tipos</title>
</head>
<body>
<h1>Definir variables de diferentes tipos en PHP</h1>
<p>
<?php
$integerVar = 10;
echo "Valor de la variable integer: $integerVar <br>";

$doubleVar = 20.5;
echo "Valor de la variable double: $doubleVar <br>";

$stringVar = "Hola Mundo";
echo "Valor de la variable string: $stringVar <br>";

$booleanVar = true;
echo "Valor de la variable boolean: $booleanVar <br>";
?>
</p>
</body>
</html>
