<html>
<head>
    <title>Formulario de Contrato</title>
</head>
<body>
    <h1>Formulario de Modificación de Contrato</h1>
    <form action="PRACTICA14.1.php" method="post">
        <label for="contract">Contrato:</label><br>
        <textarea id="contract" name="contract" rows="10" cols="50">
En la ciudad de [……..], se acuerda entre la Empresa [……..] representada por el Sr. [	] en su carácter
de Apoderado, con domicilio en la calle [……..] y el Sr. [……..], futuro empleado con domicilio en [	],
celebrar el presente contrato a Plazo Fijo, de acuerdo a la normativa vigente de los articulos 90, 92, 93, 94, 95 y concordantes de la Ley de Contrato de Trabajo No. 20744.
        </textarea><br><br>
        <input type="submit" value="Enviar Modificaciones">
    </form>
</body>
</html>
