<html>
<head>
    <title>Formulario de Edad</title>
</head>
<body>
    <h1>Formulario de Edad</h1>
    <form action="PRACTICA110.1.php" method="post">
        <label for="name">Nombre:</label>
        <input type="text" id="name" name="name" required><br><br>

        <label for="age">Edad:</label>
        <input type="number" id="age" name="age" required><br><br>

        <input type="submit" value="Enviar">
    </form>
</body>
</html>
